{% set name = "cpprb" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ymd-h/cpprb/archive/v{{ version }}.tar.gz
  sha256: 64436cb9d0c8935bd20fcd2d612551ffe6c58e181a269b715a734a0fd38c47a3

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - cython
    - pip
  run:
    - python

test:
  imports:
    - cpprb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ymd_h.gitlab.io/cpprb/
  summary: cpprb is a python (CPython) module providing replay buffer classes for reinforcement learning.
  license: MIT
  license_family: MIT
  license_file: LICENSE

  # The doc_url and dev_url are optional.
  doc_url: https://ymd_h.gitlab.io/cpprb/

extra:
  recipe-maintainers:
    - jamartinh
